version: "3.7"

# 컴퓨터들

# 내백엔드컴퓨터:
#   build:
#     파일경로: .
#     파일명: Dockerfile

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 4000:4000

  my-database:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports: 
      - 27017:27017
